export default {
    baseLineLabel: null,
    baseLineValue: null,
    // colorSet:
    cumulativeValues: false,
    domainAxisLabel: null,
    hideEmptyRowItems: 'NONE',
    hideLegend: false,
    noSpaceBetweenColumns: false,
    percentStackedValues: false,
    rangeAxisDecimals: null,
    rangeAxisLabel: null,
    rangeAxisMaxValue: null,
    rangeAxisMinValue: null,
    rangeAxisSteps: null,
    regressionType: 'NONE',
    showData: true,
    targetLineLabel: null,
    targetLineValue: null,
    // legendDisplayStrategy
    // legendSet
    aggregationType: 'DEFAULT',
    completedOnly: false,
    hideSubtitle: false,
    hideTitle: false,
    sortOrder: 0,
    subtitle: null,
    title: null,
    // topLimit
};
