const SYSTEM_SETTING_DATE_FORMAT = 'keyDateFormat'
const SYSTEM_SETTINGS_RELATIVE_PERIOD = 'keyAnalysisRelativePeriod'
export const SYSTEM_SETTINGS_DIGIT_GROUP_SEPARATOR =
    'keyAnalysisDigitGroupSeparator'
export const SYSTEM_SETTINGS_HIDE_DAILY_PERIODS = 'keyHideDailyPeriods'
export const SYSTEM_SETTINGS_HIDE_WEEKLY_PERIODS = 'keyHideWeeklyPeriods'
export const SYSTEM_SETTINGS_HIDE_BIWEEKLY_PERIODS = 'keyHideBiWeeklyPeriods'
export const SYSTEM_SETTINGS_HIDE_MONTHLY_PERIODS = 'keyHideMonthlyPeriods'
export const SYSTEM_SETTINGS_HIDE_BIMONTHLY_PERIODS = 'keyHideBiMonthlyPeriods'
export const SYSTEM_SETTINGS_IGNORE_ANALYTICS_APPROVAL_YEAR_THRESHOLD =
    'keyIgnoreAnalyticsApprovalYearThreshold'

export const systemSettingsKeys = [
    SYSTEM_SETTING_DATE_FORMAT,
    SYSTEM_SETTINGS_RELATIVE_PERIOD,
    SYSTEM_SETTINGS_DIGIT_GROUP_SEPARATOR,
    SYSTEM_SETTINGS_HIDE_DAILY_PERIODS,
    SYSTEM_SETTINGS_HIDE_WEEKLY_PERIODS,
    SYSTEM_SETTINGS_HIDE_BIWEEKLY_PERIODS,
    SYSTEM_SETTINGS_HIDE_MONTHLY_PERIODS,
    SYSTEM_SETTINGS_HIDE_BIMONTHLY_PERIODS,
    SYSTEM_SETTINGS_IGNORE_ANALYTICS_APPROVAL_YEAR_THRESHOLD,
]
