export const USER_SETTINGS_UI_LOCALE = 'keyUiLocale'
export const USER_SETTINGS_DISPLAY_PROPERTY = 'keyAnalysisDisplayProperty'

export const DERIVED_USER_SETTINGS_DISPLAY_NAME_PROPERTY =
    'DERIVED_USER_SETTINGS_DISPLAY_NAME_PROPERTY'

export const userSettingsKeys = [
    USER_SETTINGS_UI_LOCALE,
    USER_SETTINGS_DISPLAY_PROPERTY,
]
