import {
    DIMENSION_ID_DATA,
    DIMENSION_ID_ORGUNIT,
    visTypeDisplayNames,
    VIS_TYPE_SCATTER,
    AXIS_ID_ROWS,
} from '@dhis2/analytics'

import { openDimension } from '../../elements/dimensionsPanel'
import {
    selectIndicators,
    clickDimensionModalUpdateButton,
    switchDataTab,
} from '../../elements/dimensionModal'
import { changeVisType } from '../../elements/visualizationTypeSelector'
import {
    expectErrorToContainTitle,
    expectStartScreenToBeVisible,
    goToStartPage,
} from '../../elements/startScreen'
import { expectStoreCurrentColumnsToHaveLength } from '../../utils/store'
import { expectVisualizationToBeVisible } from '../../elements/chart'
import { TEST_INDICATORS } from '../../utils/data'
import { clickMenuBarUpdateButton } from '../../elements/menuBar'
import {
    clickContextMenuSwap,
    expectDimensionOnAxisToHaveLockIcon,
    expectDimensionOnAxisToHaveWarningIcon,
    openContextMenu,
    openDimensionOnAxis,
} from '../../elements/layout'
import { deleteAO, saveExistingAO, saveNewAO } from '../../elements/fileMenu'
import { expectRouteToBeEmpty } from '../../elements/route'

const TEST_INDICATOR_NAMES = TEST_INDICATORS.slice(1, 4).map(item => item.name)
const TEST_VIS_NAME = `TEST SCATTER ${new Date().toLocaleString()}`
const TEST_VIS_DESCRIPTION = 'Generated by Cypress'

describe('using a Scatter chart', () => {
    it('navigates to a new Scatter chart', () => {
        goToStartPage()
        changeVisType(visTypeDisplayNames[VIS_TYPE_SCATTER])
    })
    it("shows an error message when vertical and horizontal isn't selected", () => {
        clickMenuBarUpdateButton()
        expectErrorToContainTitle('Vertical is empty')
    })
    it('adds a vertical item and shows an error message', () => {
        openDimension(DIMENSION_ID_DATA)
        selectIndicators([TEST_INDICATOR_NAMES[0]])
        clickDimensionModalUpdateButton()
        expectErrorToContainTitle('Horizontal is empty')
        expectVerticalToContainDimensionLabel(TEST_INDICATOR_NAMES[0])
    })
    it('adds a horizontal item and displays a chart', () => {
        openDimension(DIMENSION_ID_DATA)
        switchDataTab('Horizontal')
        selectIndicators([TEST_INDICATOR_NAMES[1]])
        clickDimensionModalUpdateButton()
        expectVisualizationToBeVisible(VIS_TYPE_SCATTER)
        expectStoreCurrentColumnsToHaveLength(1)
        expectVerticalToContainDimensionLabel(TEST_INDICATOR_NAMES[0])
        expectHorizontalToContainDimensionLabel(TEST_INDICATOR_NAMES[1])
    })
    it('Data is locked to Vertical', () => {
        expectDimensionOnAxisToHaveLockIcon(DIMENSION_ID_DATA, 'Vertical')
    })
    it('Data is locked to Horizontal', () => {
        expectDimensionOnAxisToHaveLockIcon(DIMENSION_ID_DATA, 'Horizontal')
    })
    it('Org units is locked to Points', () => {
        expectDimensionOnAxisToHaveLockIcon(DIMENSION_ID_ORGUNIT, AXIS_ID_ROWS)
    })
    it('swaps vertical with horizontal', () => {
        openContextMenu('VERTICAL')
        clickContextMenuSwap('VERTICAL', 'HORIZONTAL')
        clickMenuBarUpdateButton()
        expectVisualizationToBeVisible(VIS_TYPE_SCATTER)
        expectVerticalToContainDimensionLabel(TEST_INDICATOR_NAMES[1])
        expectHorizontalToContainDimensionLabel(TEST_INDICATOR_NAMES[0])
    })
    it('adds a second item to horizontal and displays warning messages', () => {
        openDimensionOnAxis(DIMENSION_ID_DATA, 'Horizontal')
        selectIndicators([TEST_INDICATOR_NAMES[2]])
        // TODO: expect the Data dimension selected list to display a warning message (next PR)
        clickDimensionModalUpdateButton()
        expectDimensionOnAxisToHaveWarningIcon(DIMENSION_ID_DATA, 'Horizontal')
    })
    it('saves and only displays 1 horizontal item', () => {
        saveNewAO(TEST_VIS_NAME, TEST_VIS_DESCRIPTION)
        expectVisualizationToBeVisible(VIS_TYPE_SCATTER)
        expectVerticalToContainDimensionLabel(TEST_INDICATOR_NAMES[1])
        expectHorizontalToContainDimensionLabel(TEST_INDICATOR_NAMES[0])
    })
    it('swaps vertical with horizontal', () => {
        openContextMenu('HORIZONTAL')
        clickContextMenuSwap('HORIZONTAL', 'VERTICAL')
        clickMenuBarUpdateButton()
        expectVisualizationToBeVisible(VIS_TYPE_SCATTER)
        expectVerticalToContainDimensionLabel(TEST_INDICATOR_NAMES[0])
        expectHorizontalToContainDimensionLabel(TEST_INDICATOR_NAMES[1])
    })
    it('saves and displays items in the correct places', () => {
        saveExistingAO()
        expectVisualizationToBeVisible(VIS_TYPE_SCATTER)
        expectVerticalToContainDimensionLabel(TEST_INDICATOR_NAMES[0])
        expectHorizontalToContainDimensionLabel(TEST_INDICATOR_NAMES[1])
    })
    it('deletes saved scatter AO', () => {
        deleteAO()
        expectRouteToBeEmpty()
        expectStartScreenToBeVisible()
    })
})

const expectVerticalToContainDimensionLabel = label =>
    cy.getBySel('Vertical-axis').should('contain', label)
const expectHorizontalToContainDimensionLabel = label =>
    cy.getBySel('Horizontal-axis').should('contain', label)
