//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by d2-i18n-generate.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import i18n from '@dhis2/d2-i18n'

import csTranslations from './cs/translations.json'
import enTranslations from './en/translations.json'
import esTranslations from './es/translations.json'
import frTranslations from './fr/translations.json'
import idTranslations from './id/translations.json'
import nbTranslations from './nb/translations.json'
import ptTranslations from './pt/translations.json'
import ukTranslations from './uk/translations.json'
import uzTranslations from './uz/translations.json'
import zhTranslations from './zh/translations.json'

const namespace = 'default'
i18n.addResources('cs', namespace, csTranslations)
i18n.addResources('en', namespace, enTranslations)
i18n.addResources('es', namespace, esTranslations)
i18n.addResources('fr', namespace, frTranslations)
i18n.addResources('id', namespace, idTranslations)
i18n.addResources('nb', namespace, nbTranslations)
i18n.addResources('pt', namespace, ptTranslations)
i18n.addResources('uk', namespace, ukTranslations)
i18n.addResources('uz', namespace, uzTranslations)
i18n.addResources('zh', namespace, zhTranslations)

export default i18n
