name: 'dhis2: test (node)'

on: push

jobs:
    unit:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install --frozen-lockfile

            # Build is required by plugin tests below
            - name: Build
              run: yarn build

            - name: Lint
              run: |
                  yarn d2-style js check
                  yarn d2-style text check

            - name: Test
              run: yarn test
        env:
            CI: true
