name: 'dhis2: publish (node)'

on:
    push:
        branches:
            - master
            - next
            - next-major
            - alpha
            - beta
            - '[0-9]+.x'
            - '[0-9]+.x.x'
            - '[0-9]+.[0-9]+.x'

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    NPM_TOKEN: ${{secrets.DHIS2_BOT_NPM_TOKEN}}
    GH_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}

jobs:
    publish:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{env.GH_TOKEN}}
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test

            - name: Publish to NPM
              run: npx @dhis2/cli-utils release --publish npm
        env:
            CI: true
